name: Continuous Integration

on: [push, pull_request]

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.8
      - name: Install verilator
        run: apt-get update && apt-get install verilator -y
      - name: Cache Scala
        uses: coursier/cache-action@v5
      - name: Run tests
        run: make test